p, q, r = eval(input('Enter Three Numbers: '))
print('p = ', p, 'q = ', q, 'r = ', r)
print('(p > q > r) is', p > q > r )
print('(p < q < r) is ', p < q < r)
print('(p < q ) and (q  < r) is', (p < q) and (q < r ))
print('(p < q) or (q < r) is ', (p <  q) or (q <  r))